name: Android Native CI

on:
  workflow_call:

jobs:
  android-native:
    name: Android Native App

    runs-on:
      - self-hosted
      - macOS
      - ARM64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Android Device
        run: |
          adb devices
          DEVICE_COUNT=$(adb devices | awk 'NR > 1 && $2 == "device" {count++} END {print count+0}')
          if [ "$DEVICE_COUNT" -eq 0 ]; then
            echo "❌ No Android device connected."
            exit 1
          fi
          echo "✅ Found $DEVICE_COUNT Android device(s)"

      - name: Start Appium
        run: |
          appium --allow-insecure chromedriver_autodownload > appium.log 2>&1 &

      - name: Wait for Appium
        run: |
          for i in {1..30}; do
            curl http://127.0.0.1:4723/status && exit 0
            sleep 2
          done
          exit 1

      - name: Run Android Tests
        run: |
          mvn clean test \
            -DisRemote=false \
            -DtestSuite=src/main/resources/Android.xml \
            -Dudid=${{ vars.ANDROID_UDID }}

      - name: Upload android allure results
        uses: actions/upload-artifact@v4
        with:
          name: android-allure-results
          path: target/allure-results